=== KonstantinMakarov/Tariff/tariff.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.com/Tariff"
        xmlns:tns="http://www.epam.com/Tariff">
    <element name="tariffs">
        <complexType>
            <sequence>
                <element name="tariff" type="tns:Tariff" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Tariff">
        <sequence>
            <element name="name" type="tns:Name" />
            <element name="operatorName" type="tns:OperatorName" />
            <element name="payroll" type="double" />
            <element name="smsPrice" type="double" />
            <element name="callPrice" type="tns:CallPrice" />
            <element name="parameter" type="tns:Parameter" />
        </sequence>
    </complexType>

    <simpleType name="Name">
        <restriction base="string">
            <pattern value="[a-zA-Z]+"/>
        </restriction>
    </simpleType>

    <simpleType name="OperatorName">
        <restriction base="string">
            <pattern value="[a-zA-Z]+"/>
        </restriction>
    </simpleType>

    <complexType name="CallPrice">
        <sequence>
            <element name="intraCallPrice" type="double"/>
            <element name="externalCallPrice" type="double"/>
            <element name="landLineCallPrice" type="double"/>
        </sequence>
    </complexType>

    <complexType name="Parameter">
        <sequence>
            <element name="hasFavouriteNumber" type="boolean"/>
            <element name="typeTariff" type="tns:TypeTariff"/>
            <element name="getOperatorPrice" type="double"/>
        </sequence>
    </complexType>

    <simpleType name="TypeTariff">
            <restriction base="string">
                <enumeration value="twelveSecond"/>
                <enumeration value="oneMinute"/>
            </restriction>
    </simpleType>

</schema>

=== KonstantinMakarov/Tariff/tariff.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:tariffs xmlns:tns="http://www.epam.com/Tariff" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.epam.com/Tariff tariff.xsd
http://www.epam.com/Tariff ">
    <tariff>
        <name>EasyToSay</name>
        <operatorName>MTS</operatorName>
        <payroll>50000</payroll>
        <smsPrice>500</smsPrice>
        <callPrice>
            <intraCallPrice>200</intraCallPrice>
            <externalCallPrice>800</externalCallPrice>
            <landLineCallPrice>1000</landLineCallPrice>
        </callPrice>
        <parameter>
            <hasFavouriteNumber>true</hasFavouriteNumber>
            <typeTariff>oneMinute</typeTariff>
            <getOperatorPrice>10000</getOperatorPrice>
        </parameter>
    </tariff>

    <tariff>
        <name>Native</name>
        <operatorName>MTS</operatorName>
        <payroll>30000</payroll>
        <smsPrice>500</smsPrice>
        <callPrice>
            <intraCallPrice>300</intraCallPrice>
            <externalCallPrice>500</externalCallPrice>
            <landLineCallPrice>1000</landLineCallPrice>
        </callPrice>
        <parameter>
            <hasFavouriteNumber>true</hasFavouriteNumber>
            <typeTariff>twelveSecond</typeTariff>
            <getOperatorPrice>0</getOperatorPrice>
        </parameter>
    </tariff>

    <tariff>
        <name>NewNorm</name>
        <operatorName>Velcom</operatorName>
        <payroll>60000</payroll>
        <smsPrice>200</smsPrice>
        <callPrice>
            <intraCallPrice>100</intraCallPrice>
            <externalCallPrice>800</externalCallPrice>
            <landLineCallPrice>1300</landLineCallPrice>
        </callPrice>
        <parameter>
            <hasFavouriteNumber>true</hasFavouriteNumber>
            <typeTariff>oneMinute</typeTariff>
            <getOperatorPrice>20000</getOperatorPrice>
        </parameter>
    </tariff>
</tns:tariffs>
